production:
  adapter: postgresql
  encoding: unicode
  database: songer-production
  pool: 5
  username: songer
  password:

development:
  adapter: postgresql
  encoding: unicode
  database: songer-development
  pool: 5
  username: songer
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: songer-test
  pool: 5
  username: songer
  password:
